# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrackingFormat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QValidator, QRegExpValidator
from HtmlFunction import htmlf
from Main import Ui_Main
import utils

class Ui_Initial(object):
    def setupUi(self, MainWindow):
        self._frameTimer = QtCore.QTimer()
        self._frameTimer.start(10)
        self._frameTimer.timeout.connect(self.checkMainClosed)

        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(654, 470)

        self.workoutLabel = QtWidgets.QLabel(MainWindow)
        self.workoutLabel.setGeometry(QtCore.QRect(120, 10, 401, 51))
        self.workoutLabel.setAutoFillBackground(False)
        self.workoutLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.workoutLabel.setMidLineWidth(4)
        self.workoutLabel.setObjectName("workoutLabel")

        self.startBtn = QtWidgets.QPushButton(MainWindow)
        self.startBtn.setGeometry(QtCore.QRect(210, 330, 211, 51))
        self.startBtn.setObjectName("startBtn")

        self.setNumberLineEdit = QtWidgets.QLineEdit(MainWindow)
        self.setNumberLineEdit.setValidator(QRegExpValidator(QRegExp("[0-9]*")))
        self.setNumberLineEdit.setGeometry(QtCore.QRect(220, 80, 111, 31))
        self.setNumberLineEdit.setObjectName("setNumberLineEdit")

        self.setNumberLabel = QtWidgets.QLabel(MainWindow)
        self.setNumberLabel.setGeometry(QtCore.QRect(330, 80, 61, 31))
        self.setNumberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.setNumberLabel.setObjectName("setNumberLabel")

        self.jumpingJacksLabel = QtWidgets.QLabel(MainWindow)
        self.jumpingJacksLabel.setGeometry(QtCore.QRect(170, 140, 141, 31))
        self.jumpingJacksLabel.setObjectName("jumpingJacksLabel")

        self.jumpingJacks = QtWidgets.QComboBox(MainWindow)
        self.jumpingJacks.setGeometry(QtCore.QRect(330, 140, 101, 31))
        self.jumpingJacks.setObjectName("jumpingJacks")

        self.weightCurlsLabel = QtWidgets.QLabel(MainWindow)
        self.weightCurlsLabel.setGeometry(QtCore.QRect(170, 240, 141, 31))
        self.weightCurlsLabel.setObjectName("weightCurlsLabel")

        self.weightCurls = QtWidgets.QComboBox(MainWindow)
        self.weightCurls.setGeometry(QtCore.QRect(330, 240, 101, 31))
        self.weightCurls.setObjectName("weightCurls")

        self.squats = QtWidgets.QComboBox(MainWindow)
        self.squats.setGeometry(QtCore.QRect(330, 190, 101, 31))
        self.squats.setObjectName("squats")

        self.squatsLabel = QtWidgets.QLabel(MainWindow)
        self.squatsLabel.setGeometry(QtCore.QRect(170, 190, 141, 31))
        self.squatsLabel.setObjectName("squatsLabel")

        for i in range(5, 30, 5):
            self.jumpingJacks.addItem(str(i))
            self.squats.addItem(str(i))
            self.weightCurls.addItem(str(i))

        # This section is devoted to button connections
        self.startBtn.clicked.connect(self.startBtnAction)

        self.reTranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def startBtnAction(self):
        if len(self.setNumberLineEdit.text()) <= 0:
            _translate = QtCore.QCoreApplication.translate
            self.startBtn.setText(_translate("MainWindow", "Input Set Number"))
        else:
            self.mainWindow = QtWidgets.QMainWindow()
            self.ui = Ui_Main()
            # Params
            self.ui.setParams(
                self.setNumberLineEdit.text(),
                self.jumpingJacks.currentText(),
                self.squats.currentText(),
                self.weightCurls.currentText())

            utils.tracker = utils.ExerciseTracker(
                int(self.setNumberLineEdit.text()),
                int(self.jumpingJacks.currentText()),
                int(self.squats.currentText()),
                int(self.weightCurls.currentText()), self)
            print("tracker created")
            # Ui
            self.ui.setupUi(self.mainWindow)
            # Window
            MainWindow.hide()
            self.mainWindow.show()
            self.bool = True

    def checkMainClosed(self):
        try:
            if self.mainWindow.isActiveWindow() == False and self.bool:
                MainWindow.show()
                self.bool = False
        except:
            pass

    def reTranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.workoutLabel.setText(_translate("MainWindow", htmlf([("Workout", "ib")])))
        self.startBtn.setText(_translate("MainWindow", "START"))
        self.setNumberLabel.setText(_translate("MainWindow", "SETS"))
        self.jumpingJacksLabel.setText(_translate("MainWindow", "Jumping Jacks"))
        self.squatsLabel.setText(_translate("MainWindow", "Squats"))
        self.weightCurlsLabel.setText(_translate("MainWindow", "Weight Curls"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    with open("styles/styleLight.qss", "r") as styleFile:
        stylesheet = "\n".join(styleFile.readlines())
    app.setStyleSheet(stylesheet)
    ui = Ui_Initial()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
